name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps or minimal code to reproduce
      placeholder: |
        1. Run `framecode render code.ts`
        2. ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `framecode --version`
      placeholder: "0.1.0"

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Linux
        - Windows
