name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like? Why is it useful?
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Solution
      description: How should it work? (optional)
      placeholder: |
        ```bash
        framecode render code.ts --new-flag
        ```

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CLI
        - Animations
        - Themes
        - Export/Rendering
        - Web
        - Infrastructure
        - Other
